name: Integration Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build and Test React App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t testimage -f Dockerfile.dev .

      - name: Run Jest tests
        run: docker run -e CI=true testimage npm run test -- --coverage
