name: Integration Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-docker-react-app:
    name: A job to build docker image of react app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t testimage -f Dockerfile.dev .

  test-docker-react-app:
    name: A job to run tests in created docker image for react app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Docker Image
        run: docker run -e CI=true testimage npm run test -- --coverage
